// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf8qulowfQuEqDU3h1N4JtpWo18oGiopI',
    appId: '1:358940279855:web:8ee5215b6d043a137872da',
    messagingSenderId: '358940279855',
    projectId: 'instaclone-c4abc',
    authDomain: 'instaclone-c4abc.firebaseapp.com',
    storageBucket: 'instaclone-c4abc.appspot.com',
    measurementId: 'G-5JM45SB67Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0YdYuPS0BW03yYvJGaqG_JKxqTv5lLRU',
    appId: '1:358940279855:android:aea68fb6240e8c227872da',
    messagingSenderId: '358940279855',
    projectId: 'instaclone-c4abc',
    storageBucket: 'instaclone-c4abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq3LvamCq5ieKOyxuvHk1L_t9_9WkIcGg',
    appId: '1:358940279855:ios:a3d0e3507de425447872da',
    messagingSenderId: '358940279855',
    projectId: 'instaclone-c4abc',
    storageBucket: 'instaclone-c4abc.appspot.com',
    iosBundleId: 'com.example.instaclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq3LvamCq5ieKOyxuvHk1L_t9_9WkIcGg',
    appId: '1:358940279855:ios:1c19bf98aecf10e27872da',
    messagingSenderId: '358940279855',
    projectId: 'instaclone-c4abc',
    storageBucket: 'instaclone-c4abc.appspot.com',
    iosBundleId: 'com.example.instaclone.RunnerTests',
  );
}
